firststepcm/core/urls.py
from django.urls import path 
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from .views import  IndexView ,SinglelView , PostsView ,AddView ,EditView ,Delete

app_name = "core"

urlpatterns = [
   
    path ('', login_required(IndexView.as_view()) , name = 'index'),
    path ('add/', AddView.as_view() , name = 'addview'),
    path ('posts/', staff_member_required(PostsView.as_view()) , name = 'posts'),
    path ('<slug:slug>/', SinglelView.as_view() , name = 'singleview'),
    path ('edit/<int:pk>/', EditView.as_view() , name = 'EditView'),
    path ('delete/<int:pk>/', Delete.as_view() , name = 'delete'),
]

firststepcm/firststepcm/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',user_views.register , name = 'register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html ') , name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html ') , name = 'logout'),
    path ('', include('core.urls' , namespace = 'core')),
    path ('', include('users.urls' , namespace = 'users')),
    
   
] 



urlpatterns += static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

firststepcm/users/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views


app_name = 'users'

urlpatterns = [
    
    path('register/',user_views.register , name = 'register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html ') , name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html ') , name = 'logout'),
  
   
] 

firststepcm/core/models.py
from django.db import models

from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User 
from ckeditor.fields import RichTextField




# Create your models here.
class Core(models.Model):

    title = models.CharField(max_length=200)
    excpert =RichTextField(null=True , blank=True)
    # excpert = models.TextField(null=True) 
    author = models.ForeignKey(User , on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200 , unique=True)
    image = models.ImageField(upload_to ='uploads/')
    updated = models.DateTimeField(auto_now=True)
    puplished = models.DateTimeField(default=timezone.now)



    def get_absolute_url(self):
        return reverse("core:singleview", args=[self.slug] )
        
    def posts_absolute_url(self):
        return reverse("core:posts" )

    def form_absolute_url(self):
        return reverse("core:posts" )   

    def edit_absolute_url(self):
        return reverse("core:EditView" , args=[self.pk])  

    def edit_absolute_url(self):
        return reverse("core:EditView" , args=[self.pk]) 


    def delete_absolute_url(self):
        return reverse("core:delete" , args=[self.pk])       
    
    class Meta:

        ordering = ['-puplished']
        verbose_name_plural = 'Core'


    def __str__(self):

        return self.title     

firststepcm/users/models.py
from django.db import models

# Create your models here.

firststepcm/core/forms.py
from django import forms 
from .models import Core
from django.contrib.auth.models import User



class PostForm(forms.ModelForm):

    
    class Meta:
        
        model  = User
        fields = '__all__'

firststepcm/users/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input label','placeholder': 'Enter your password'}),max_length=40, min_length=8)
    password2 = forms.CharField(max_length=40, min_length=8, label="Repeat password", widget=forms.PasswordInput(attrs={'class': 'input label','placeholder': 'Repeat password'}))

    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'input', 'autofocus': True ,'placeholder': 'Enter your username'}),
            'email': forms.EmailInput(attrs={'class': 'input', 'required': True ,'placeholder': 'Enter your email'}),
            # 'password':forms.PasswordInput(attrs={'class': 'input'}),
            # 'password2':forms.PasswordInput(attrs={'class': 'input'}),
        }

    

        

firststepcm/core/views.py
from django.shortcuts import render , redirect
from django.views.generic import ListView , DetailView , UpdateView ,CreateView , DeleteView
from .models import *
from django.urls import reverse_lazy
from django.contrib import messages

# Create your views here.

class IndexView(ListView):
    model = Core
    template_name = 'core/core_list.html'


class SinglelView(DetailView):
    model = Core
    template_name = "core/single.html"
    context_object_name = 'post'

class PostsView(ListView):
    model = Core
    template_name = 'core/posts.html'
    context_object_name = 'post_list'

class AddView(CreateView):
    model = Core
    template_name = 'core/add.html'
    fields = '__all__'
    success_url = reverse_lazy('core:posts')

class EditView(UpdateView):
    model = Core
    template_name = 'core/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')


class Delete(DeleteView):
    model = Core
    template_name = 'core/confirm-delete.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')

   

firststepcm/users/views.py
from django.contrib import messages
from django.shortcuts import render , redirect
from users.forms import RegisterForm 
from django.forms import ValidationError
# Create your views here.


def register(request):
    if request.method == 'POST':
        
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')

            # email = form.cleaned_data.get('email')
            # password1 = form.cleaned_data.get('password1')
            # password2 = form.cleaned_data.get('password2')
            # # form = RegisterForm(username=username,email=email,password=password,password2=password2)
            
            messages.success(request,f'Your account has been created you are now able to login')

            return redirect("users:login")
    else:
        form =   RegisterForm()  
    return render (request , 'users/register.html ', {'form':form})    

firststepcm/templates/core/add.html
{% extends 'core/base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<div class="container pt-5 ">
    <h1 class="text-center">Add Post</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form | crispy}}
        <div class="form-group">
            <label for="">{{ field.label }}</label>

            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}

        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> submit

            </button>
            <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

firststepcm/templates/core/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
    <title>Hello, world!</title>
</head>

<body>
    {% include 'core/navbar.html' %}
    <div class="container text-center">

        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    {% block content%}

    {% endblock%}

    {% include 'core/footer.html' %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</body>

</html>

firststepcm/templates/core/confirm-delete.html
{% extends 'core/base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<div class="container pt-5 ">
    <h1 class="text-center">Delete Post</h1>
    <form method="post">
        {% csrf_token %}


        <p>Are you sure you want to delete "{{object}}"?</p>

        <button type="submit" class="btn btn-success" value="">confirm</button>

    </form>
</div>
{% endblock %}

firststepcm/templates/core/core_list.html
{% extends 'core/base.html' %}

{% load static %}

{% block content%}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for core in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class='card-img-top' src="{{ core.image.url }}" alt='card image cap' width="500" height="300">
                    <div class="card-body">
                        <h4 class=""><a href="{{core.get_absolute_url}}">{{core.title}}</a></h4>
                        <!-- <p class="card-text">{{core.excpert}}</p> -->
                        <div class="d-flex justify-content-center align-items-center">
                            <div class="">
                                <small class="text-muted">{{core.puplished}}</small>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>

{% endblock%}

firststepcm/templates/core/edit.html
{% extends 'core/base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<div class="container pt-5 ">
    <h1 class="text-center">Add Post</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form | crispy}}
        <div class="form-group">
            <label for="">{{ field.label }}</label>

            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}

        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> submit

            </button>
            <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

firststepcm/templates/core/footer.html
<!-- Footer -->
<footer class="page-footer font-small indigo">

    <!-- Footer Links -->
    <div class="container text-center text-md-left">

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-3 mx-auto">

                <!-- Links -->


                <ul class="list-unstyled">
                    <li>
                        <a href="#!">Very long link 1</a>
                    </li>

                </ul>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-3 mx-auto">

                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4">about</h5>

                <ul class="list-unstyled">


                </ul>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-3 mx-auto">

                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4">contact us</h5>

                <ul class="list-unstyled">

                </ul>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-3 mx-auto">

                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

                <ul class="list-unstyled">


                </ul>

            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->

firststepcm/templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item active" href="#">
                <a class="nav-link" href="/">Home</a>
            </li>
            {% if request.user.is_staff %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:posts' %}">Manage Posts</a>
            </li>
            {% endif %}

            {% if user.is_authenticated %}
            <li class="nav-item active" href="#">
                <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
            </li>

            {% else %}
            <li class="nav-item active" href="#">
                <a class="nav-link" href="{% url 'users:login'%}">Log in</a>

            </li>
            <li>
                <a class="nav-link" href="{% url 'users:register' %}">Sign Up</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

firststepcm/templates/core/posts.html
{% extends 'core/base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-brand" href="#">Post Adminstration</div>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:addview' %}">Add New</a>
            </li>
        </ul>
    </div>
</nav>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for post in post_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class='card-img-top' src="{{ post.image.url }}" alt='card image cap' width="500" height="300">
                    <div class="card-body">
                        <h4 class="lead"><a class='text-dark' href="#">{{post.title}}</a></h4>
                        <p class="card-text"></p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{{post.get_absolute_url}}" class="btn btn-sm btn-outline-primary" role="button"
                                    aria-pressed='true'>View</a>

                                <a href="{{post.edit_absolute_url}}" class="btn btn-sm btn-outline-primary"
                                    role="button" aria-pressed='true'>Edit</a>

                                <a href="{{post.delete_absolute_url}}" class="btn btn-sm btn-outline-danger"
                                    role="button" aria-pressed='true'>Delete</a>
                            </div>
                            <small class='text-muted'>9 min</small>
                        </div>

                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock  %}

firststepcm/templates/core/single.html
{% extends 'core/base.html' %}



{% block content%}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class='card-img-top' src='{{post.image.url}}' alt='card image cap' width="500" height="300">
                    <div class="card-body">
                        <h4 class="">{{post.title}}</h4>

                        <div class="d-flex justify-content-center align-items-center">
                            <div class="">
                                <small class="text-muted">{{post.puplished}}</small>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <p>{{post.excpert}}</p>
            </div>
        </div>
    </div>
</div>

{% endblock%}

firststepcm/users/templates/users/login.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block content%}
<div class="container">
    <div class="columns is-mobile">
        <div class="column is-half is-offset-one-quarter">
            <div class="content">
                <h2>Log In</h2>
            </div>
            <form action="{% url 'login' %}" method="post">
                {% csrf_token %}
                {% for non_field_error in form.non_field_errors %}
                <p class="help is-danger">{{ non_field_error }}</p>
                {% endfor %}
                {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}" class="label">{{ field.html_name }}</label>
                    {{ field }}
                    {% if help_text %}
                    <p class="help">{{field.help_text}}</p>
                    {% endif %}
                    {% for error in field.errors %}
                    <p class="help is-danger">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
                <input type="submit" value="log in" class="button is-primary mb-4">
                <p>Not have account <a href="{% url 'users:register' %}">Register</a></p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

firststepcm/users/templates/users/logout.html
{% extends 'core/base.html' %}

{% block content%}
<div class="container">
    <div class="columns is-mobile">
        <div class="column is-half is-offset-one-quarter">
            <div class="content p-4">
                <h2>You have been logged out</h2>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    <a class="m-4" href="{% url 'users:login'  %}">Log In Again</a>
                </small>
            </div>
        </div>
    </div>
</div>
{% endblock %}

firststepcm/users/templates/users/register.html
{% extends 'core/base.html' %}

{% block content%}
<div class="container">
    <div class="columns is-mobile">
        <div class="column is-half is-offset-one-quarter">
            <div class="content">
                <h2>Register</h2>
            </div>
            <form action="{% url 'register' %}" method="post">
                {% csrf_token %}

                {% for non_field_error in form.non_field_errors %}
                <p class="help is-danger">{{ non_field_error }}</p>
                {% endfor %}
                {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}" class="label">{{ field.html_name }}</label>
                    {{ field }}
                    {% if help_text %}
                    <p class="help">{{field.help_text}}</p>
                    {% endif %}
                    {% for error in field.errors %}
                    <p class="help is-danger">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
                <input type="submit" value="SIGN UP" class="button is-primary mp-4">
            </form>
        </div>
    </div>
</div>
{% endblock %}